#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Woflo Labs
# SPDX-License-Identifier: GPL-3.0-or-later
# Additional permission: Neuron-Woflo exception; see repository-root LICENSE.md.
#
# Push `.github/labels.yml` onto the repo's label set. Idempotent: `--force` turns
# create into upsert, so running it twice changes nothing the second time.
#
# Never deletes. A label added by hand survives a sync and shows up in the "not in
# labels.yml" report at the end instead, since silent deletion would un-triage every
# issue carrying it.
#
# Usage:  bash .github/sync-labels.sh [--dry-run] [owner/repo]
set -euo pipefail

DRY=0
[ "${1:-}" = "--dry-run" ] && { DRY=1; shift; }
REPO="${1:-}"
GH_ARGS=()
[ -n "$REPO" ] && GH_ARGS=(--repo "$REPO")

SRC="$(dirname "$0")/labels.yml"
[ -f "$SRC" ] || { echo "missing $SRC" >&2; exit 1; }

# Parse the `- name: / color: / description:` triples. Deliberately a dumb line
# scanner rather than a yaml dependency: the file is generated by hand in exactly
# this shape, and a sync script that needs an install step doesn't get run.
declare -a NAMES=()
name=""; color=""; desc=""
flush() {
  [ -z "$name" ] && return 0
  NAMES+=("$name")
  if [ "$DRY" = 1 ]; then
    printf '  %-22s #%s  %s\n' "$name" "$color" "$desc"
  else
    gh label create "$name" --color "$color" --description "$desc" --force "${GH_ARGS[@]}" >/dev/null
    printf '  ok  %s\n' "$name"
  fi
  name=""; color=""; desc=""
}

strip() { sed -e 's/^ *//' -e 's/ *$//' -e 's/^"\(.*\)"$/\1/'; }

while IFS= read -r line; do
  case "$line" in
    '#'*|'') continue ;;
    '  - name:'*) flush; name="$(printf '%s' "${line#*name:}" | strip)" ;;
    '    color:'*) color="$(printf '%s' "${line#*color:}" | strip)" ;;
    '    description:'*) desc="$(printf '%s' "${line#*description:}" | strip)" ;;
  esac
done < "$SRC"
flush

echo
echo "labels in the repo but NOT in labels.yml (nothing was deleted):"
gh label list --limit 200 "${GH_ARGS[@]}" --json name --jq '.[].name' \
  | grep -vxF -f <(printf '%s\n' "${NAMES[@]}") || echo "  (none)"
